LLAMA2_CONFIG = {
    "llama2-7b": {
        "vocab_size": 32000,
        "embed_dim": 4096,
        "mlp_dim": 11008,
        "num_layers": 32,
        "num_heads": 32,
        "num_kv_heads": 32,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 10000.0,
        "tie_embeddings": False,
    },
    "llama2-7b-chat": {
        "vocab_size": 32000,
        "embed_dim": 4096,
        "mlp_dim": 11008,
        "num_layers": 32,
        "num_heads": 32,
        "num_kv_heads": 32,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 10000.0,
        "tie_embeddings": False,
    },
    "llama2-13b": {
        "vocab_size": 32000,
        "embed_dim": 5120,
        "mlp_dim": 13824,
        "num_layers": 40,
        "num_heads": 40,
        "num_kv_heads": 40,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 10000.0,
        "tie_embeddings": False,
    },
    "llama2-13b-chat": {
        "vocab_size": 32000,
        "embed_dim": 5120,
        "mlp_dim": 13824,
        "num_layers": 40,
        "num_heads": 40,
        "num_kv_heads": 40,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 10000.0,
        "tie_embeddings": False,
    },
    "llama2-70b": {
        "vocab_size": 32000,
        "embed_dim": 8192,
        "mlp_dim": 28672,
        "num_layers": 80,
        "num_heads": 64,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 10000.0,
        "tie_embeddings": False,
    },
    "llama2-70b-chat": {
        "vocab_size": 32000,
        "embed_dim": 8192,
        "mlp_dim": 28672,
        "num_layers": 80,
        "num_heads": 64,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 10000.0,
        "tie_embeddings": False,
    },
    "codellama-7b": {
        "vocab_size": 32016,
        "embed_dim": 4096,
        "mlp_dim": 11008,
        "num_layers": 32,
        "num_heads": 32,
        "num_kv_heads": 32,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "tie_embeddings": False,
    },
    "codellama-13b": {
        "vocab_size": 32016,
        "embed_dim": 5120,
        "mlp_dim": 13824,
        "num_layers": 40,
        "num_heads": 40,
        "num_kv_heads": 40,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "tie_embeddings": False,
    },
    "codellama-34b": {
        "vocab_size": 32000,
        "embed_dim": 8192,
        "mlp_dim": 22016,
        "num_layers": 48,
        "num_heads": 64,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "tie_embeddings": False,
    },
    "codellama-70b": {
        "vocab_size": 32016,
        "embed_dim": 8192,
        "mlp_dim": 28672,
        "num_layers": 80,
        "num_heads": 64,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "tie_embeddings": False,
    },
}

LLAMA2_WEIGHTS_URLS = {
    "llama2-7b": {
        "hf_id": "meta-llama/Llama-2-7b-hf",
        "gated": True,
        "safetensors": True,
    },
    "llama2-7b-chat": {
        "hf_id": "meta-llama/Llama-2-7b-chat-hf",
        "gated": True,
        "safetensors": True,
    },
    "llama2-13b": {
        "hf_id": "meta-llama/Llama-2-13b-hf",
        "gated": True,
        "safetensors": True,
    },
    "llama2-13b-chat": {
        "hf_id": "meta-llama/Llama-2-13b-chat-hf",
        "gated": True,
        "safetensors": True,
    },
    "llama2-70b": {
        "hf_id": "meta-llama/Llama-2-70b-hf",
        "gated": True,
        "safetensors": True,
    },
    "llama2-70b-chat": {
        "hf_id": "meta-llama/Llama-2-70b-chat-hf",
        "gated": True,
        "safetensors": True,
    },
    "codellama-7b": {
        "hf_id": "codellama/CodeLlama-7b-hf",
        "gated": False,
        "safetensors": True,
    },
    "codellama-13b": {
        "hf_id": "codellama/CodeLlama-13b-hf",
        "gated": False,
        "safetensors": True,
    },
    "codellama-34b": {
        "hf_id": "codellama/CodeLlama-34b-hf",
        "gated": False,
        "safetensors": True,
    },
    "codellama-70b": {
        "hf_id": "codellama/CodeLlama-70b-hf",
        "gated": False,
        "safetensors": True,
    },
}
