"""Explicit model_type -> class-name mappings for the AutoZM* loaders.

The SOURCE OF TRUTH for AutoZM* resolution (transformers' ``MODEL_MAPPING_NAMES`` pattern):
the AutoZM* classes look a repo's model_type up in these tables and resolve the class-name
string to the class lazily. Hand-maintained -- edit an entry to change what an AutoZM* loads
for a model_type, and add a row when you add a model. The offline coverage test in
``tests/integration/test_auto_registry.py`` flags a model class that is missing here.

Keys are the ``model_type`` from a zeromodels ``zm_config.json`` (the typed config's,
distinct per family) OR a raw transformers ``config.json``; both spellings are included so
the zeromodels-repo and ``hf:`` load paths share one table.
"""

# task suffix -> {model_type: ClassName}. AutoZModel is task 'Model';
# AutoZM<Task> for the rest (AutoZMDetect = 'Detect', ...).
MODEL_TASK_MAPPING_NAMES = {
    "AudioClassify": {
        "whisper": "WhisperAudioClassify",
    },
    "CTC": {
        "granite_speech5_ctc": "GraniteSpeech5CTC",
    },
    "ConditionalGenerate": {
        "deepseek_vl": "DeepseekVLConditionalGenerate",
        "deepseek_vl_hybrid": "DeepseekVLHybridConditionalGenerate",
        "gemma3": "Gemma3ConditionalGenerate",
        "gemma3n": "Gemma3nConditionalGenerate",
        "gemma3n_text": "Gemma3nConditionalGenerate",
        "gemma4": "Gemma4ConditionalGenerate",
        "gemma4_text": "Gemma4ConditionalGenerate",
        "gemma4_unified": "Gemma4UnifiedConditionalGenerate",
        "gemma4_unified_text": "Gemma4UnifiedConditionalGenerate",
        "glm4v": "Glm4vConditionalGenerate",
        "glm4v_moe": "Glm4vMoeConditionalGenerate",
        "granite_speech": "GraniteSpeechConditionalGenerate",
        "granite_speech_plus": "GraniteSpeechPlusConditionalGenerate",
        "internvl": "InternVLConditionalGenerate",
        "janus": "JanusConditionalGenerate",
        "kimi_k25": "KimiK25ConditionalGenerate",
        "locateanything": "LocateAnythingConditionalGenerate",
        "minimax_m3_vl": "MiniMaxM3VLConditionalGenerate",
        "mistral3": "Mistral3ConditionalGenerate",
        "moonshine": "MoonshineConditionalGenerate",
        "qwen2_5_vl": "Qwen2_5VLConditionalGenerate",
        "qwen2_vl": "Qwen2VLConditionalGenerate",
        "qwen3_5": "Qwen3_5ConditionalGenerate",
        "qwen3_5_moe": "Qwen3_5MoeConditionalGenerate",
        "qwen3_5_moe_text": "Qwen3_5MoeConditionalGenerate",
        "qwen3_5_text": "Qwen3_5ConditionalGenerate",
        "qwen3_vl": "Qwen3VLConditionalGenerate",
        "qwen3_vl_moe": "Qwen3VLMoeConditionalGenerate",
        "qwen3_vl_moe_text": "Qwen3VLMoeConditionalGenerate",
        "speech_to_text": "Speech2TextConditionalGenerate",
        "t5": "T5ConditionalGenerate",
        "whisper": "WhisperConditionalGenerate",
    },
    "DensePredict": {
        "tipsv2_dpt": "Tipsv2DptDensePredict",
    },
    "DepthEstimation": {
        "depth_anything": "DepthAnythingV2DepthEstimation",
        "tipsv2_dpt": "Tipsv2DptDepthEstimation",
    },
    "Detect": {
        "d_fine": "DFineDetect",
        "detr": "DETRDetect",
        "dfine": "DFineDetect",
        "efficientdet": "EfficientDetDetect",
        "grounding-dino": "GroundingDinoDetect",
        "owlv2": "Owlv2Detect",
        "owlvit": "OwlViTDetect",
        "rf_detr": "RFDETRDetect",
        "rt_detr": "RTDETRDetect",
        "rt_detr_v2": "RTDETRV2Detect",
        "table-transformer": "TableTransformerDetect",
    },
    "EncoderModel": {
        "t5": "T5EncoderModel",
    },
    "ImageClassify": {
        "beit": "BeitImageClassify",
        "cait": "CaiTImageClassify",
        "clip": "CLIPImageClassify",
        "convmixer": "ConvMixerImageClassify",
        "convnext": "ConvNeXtImageClassify",
        "convnextv2": "ConvNeXtV2ImageClassify",
        "deit": "DeiTImageClassify",
        "densenet": "DenseNetImageClassify",
        "efficientformer": "EfficientFormerImageClassify",
        "efficientnet": "EfficientNetImageClassify",
        "efficientnet_lite": "EfficientNetLiteImageClassify",
        "efficientnetv2": "EfficientNetV2ImageClassify",
        "flexivit": "FlexiViTImageClassify",
        "inception_next": "InceptionNextImageClassify",
        "inception_resnetv2": "InceptionResNetV2ImageClassify",
        "inceptionv3": "InceptionV3ImageClassify",
        "inceptionv4": "InceptionV4ImageClassify",
        "levit": "LevitImageClassify",
        "maxvit": "MaxViTImageClassify",
        "metaclip_2": "MetaClip2ImageClassify",
        "mit": "MiTImageClassify",
        "mlp_mixer": "MLPMixerImageClassify",
        "mobilenetv2": "MobileNetV2ImageClassify",
        "mobilenetv3": "MobileNetV3ImageClassify",
        "mobilenetv4": "MobileNetV4ImageClassify",
        "mobilevit": "MobileViTImageClassify",
        "mobilevitv2": "MobileViTV2ImageClassify",
        "nextvit": "NextViTImageClassify",
        "pit": "PiTImageClassify",
        "poolformer": "PoolFormerImageClassify",
        "pvt": "PvtImageClassify",
        "pvt_v2": "PvtV2ImageClassify",
        "regnet": "RegNetImageClassify",
        "res2net": "Res2NetImageClassify",
        "resmlp": "ResMLPImageClassify",
        "resnet": "ResNetImageClassify",
        "resnetv2": "ResNetV2ImageClassify",
        "resnext": "ResNeXtImageClassify",
        "segformer": "MiTImageClassify",
        "senet": "SENetImageClassify",
        "siglip": "SigLIPImageClassify",
        "siglip2": "SigLIP2ImageClassify",
        "swin": "SwinImageClassify",
        "swinv2": "SwinV2ImageClassify",
        "vgg": "VGGImageClassify",
        "vit": "ViTImageClassify",
        "xception": "XceptionImageClassify",
    },
    "ImageEmbed": {
        "clip": "CLIPImageEmbed",
    },
    "InstanceSegment": {
        "rf_detr": "RFDETRInstanceSegment",
    },
    "MaskedLM": {
        "bert": "BertMaskedLM",
        "deberta": "DebertaMaskedLM",
        "deberta_v2": "DebertaV2MaskedLM",
        "deberta_v3": "DebertaV3MaskedLM",
        "electra": "ElectraMaskedLM",
        "modernbert": "ModernBertMaskedLM",
        "roberta": "RobertaMaskedLM",
        "xlm-roberta": "XLMRobertaMaskedLM",
        "xlm_roberta": "XLMRobertaMaskedLM",
    },
    "Model": {
        "beit": "BeitModel",
        "bert": "BertModel",
        "cait": "CaiTModel",
        "clip": "CLIPModel",
        "convmixer": "ConvMixerModel",
        "convnext": "ConvNeXtModel",
        "convnextv2": "ConvNeXtV2Model",
        "d_fine": "DFineModel",
        "deberta": "DebertaModel",
        "deberta_v2": "DebertaV2Model",
        "deberta_v3": "DebertaV3Model",
        "deepseek_v2": "DeepseekV2Model",
        "deepseek_v3": "DeepseekV3Model",
        "deepseek_v4": "DeepseekV4Model",
        "deepseek_vl": "DeepseekVLModel",
        "deepseek_vl_hybrid": "DeepseekVLHybridModel",
        "deit": "DeiTModel",
        "densenet": "DenseNetModel",
        "depth_anything": "DepthAnythingV2Model",
        "detr": "DetrModel",
        "dfine": "DFineModel",
        "dino_resnet": "DinoResNetModel",
        "dino_vit": "DinoViTModel",
        "dinov2": "DinoV2Model",
        "dinov3_convnext": "DinoV3ConvNeXtModel",
        "dinov3_vit": "DinoV3ViTModel",
        "efficientdet": "EfficientDetModel",
        "efficientformer": "EfficientFormerModel",
        "efficientnet": "EfficientNetModel",
        "efficientnet_lite": "EfficientNetLiteModel",
        "efficientnetv2": "EfficientNetV2Model",
        "electra": "ElectraModel",
        "eomt": "EoMTModel",
        "flexivit": "FlexiViTModel",
        "gemma": "GemmaModel",
        "gemma2": "Gemma2Model",
        "gemma3": "Gemma3Model",
        "gemma3n": "Gemma3nModel",
        "gemma4": "Gemma4MultimodalModel",
        "gemma4_text": "Gemma4Model",
        "gemma4_unified": "Gemma4UnifiedModel",
        "glm": "GlmModel",
        "glm4": "Glm4Model",
        "glm4_moe": "Glm4MoeModel",
        "glm4_moe_lite": "Glm4MoeLiteModel",
        "glm4v": "Glm4vModel",
        "glm4v_moe": "Glm4vMoeModel",
        "glm_moe_dsa": "Glm5MoeModel",
        "gpt2": "GPT2Model",
        "gpt_oss": "GptOssModel",
        "granite_speech": "GraniteSpeechModel",
        "granite_speech5_ctc": "GraniteSpeech5Model",
        "granite_speech_plus": "GraniteSpeechPlusModel",
        "grounding-dino": "GroundingDinoModel",
        "inception_next": "InceptionNextModel",
        "inception_resnetv2": "InceptionResNetV2Model",
        "inceptionv3": "InceptionV3Model",
        "inceptionv4": "InceptionV4Model",
        "internvl": "InternVLModel",
        "janus": "JanusModel",
        "kimi_k25": "KimiK25Model",
        "levit": "LevitModel",
        "llama": "Llama2Model",
        "llama4": "Llama4Model",
        "llama4_text": "Llama4Model",
        "locateanything": "LocateAnythingModel",
        "mask2former": "Mask2FormerModel",
        "maskformer": "MaskFormerModel",
        "maxvit": "MaxViTModel",
        "metaclip_2": "MetaClip2Model",
        "minimax": "MiniMaxModel",
        "minimax_m2": "MiniMaxM2Model",
        "minimax_m3_vl": "MiniMaxM3VLModel",
        "mistral": "MistralModel",
        "mistral3": "Mistral3Model",
        "mit": "MiTModel",
        "mixtral": "MixtralModel",
        "mlp_mixer": "MLPMixerModel",
        "mobilenetv2": "MobileNetV2Model",
        "mobilenetv3": "MobileNetV3Model",
        "mobilenetv4": "MobileNetV4Model",
        "mobilevit": "MobileViTModel",
        "mobilevitv2": "MobileViTV2Model",
        "modernbert": "ModernBertModel",
        "moonshine": "MoonshineModel",
        "nextvit": "NextViTModel",
        "oneformer": "OneFormerModel",
        "openai-gpt": "GptModel",
        "owlv2": "Owlv2Model",
        "owlvit": "OwlViTModel",
        "pit": "PiTModel",
        "poolformer": "PoolFormerModel",
        "pvt": "PvtModel",
        "pvt_v2": "PvtV2Model",
        "qwen2": "Qwen2Model",
        "qwen2_5_vl": "Qwen2_5VLModel",
        "qwen2_moe": "Qwen2MoeModel",
        "qwen2_vl": "Qwen2VLModel",
        "qwen3": "Qwen3Model",
        "qwen3_5": "Qwen3_5VLModel",
        "qwen3_5_moe": "Qwen3_5MoeModel",
        "qwen3_5_moe_text": "Qwen3_5MoeModel",
        "qwen3_5_text": "Qwen3_5Model",
        "qwen3_moe": "Qwen3MoeModel",
        "qwen3_next": "Qwen3NextModel",
        "qwen3_vl": "Qwen3VLModel",
        "qwen3_vl_moe": "Qwen3VLMoeModel",
        "qwen3_vl_moe_text": "Qwen3VLMoeModel",
        "regnet": "RegNetModel",
        "res2net": "Res2NetModel",
        "resmlp": "ResMLPModel",
        "resnet": "ResNetModel",
        "resnetv2": "ResNetV2Model",
        "resnext": "ResNeXtModel",
        "roberta": "RobertaModel",
        "rt_detr": "RTDetrModel",
        "rt_detr_v2": "RTDetrV2Model",
        "sam": "SAMModel",
        "sam2": "SAM2Model",
        "sam2_video": "SAM2Model",
        "sam3": "SAM3Model",
        "segformer": "SegFormerModel",
        "senet": "SENetModel",
        "siglip": "SigLIPModel",
        "siglip2": "SigLIP2Model",
        "swin": "SwinModel",
        "swinv2": "SwinV2Model",
        "t5": "T5Model",
        "table-transformer": "TableTransformerModel",
        "tipsv2": "Tipsv2Model",
        "vgg": "VGGModel",
        "vit": "ViTModel",
        "whisper": "WhisperModel",
        "xception": "XceptionModel",
        "xlm-roberta": "XLMRobertaModel",
        "xlm_roberta": "XLMRobertaModel",
    },
    "MultipleChoice": {
        "bert": "BertMultipleChoice",
        "deberta_v2": "DebertaV2MultipleChoice",
        "deberta_v3": "DebertaV3MultipleChoice",
        "electra": "ElectraMultipleChoice",
        "modernbert": "ModernBertMultipleChoice",
        "roberta": "RobertaMultipleChoice",
        "xlm-roberta": "XLMRobertaMultipleChoice",
        "xlm_roberta": "XLMRobertaMultipleChoice",
    },
    "NextSentencePredict": {
        "bert": "BertNextSentencePredict",
    },
    "PanopticSegment": {
        "detr": "DETRPanopticSegment",
    },
    "QnA": {
        "bert": "BertQnA",
        "deberta": "DebertaQnA",
        "deberta_v2": "DebertaV2QnA",
        "deberta_v3": "DebertaV3QnA",
        "electra": "ElectraQnA",
        "modernbert": "ModernBertQnA",
        "roberta": "RobertaQnA",
        "t5": "T5QnA",
        "xlm-roberta": "XLMRobertaQnA",
        "xlm_roberta": "XLMRobertaQnA",
    },
    "Segment": {
        "sam": "SAMPromptableSegment",
        "sam2": "SAM2PromptableSegment",
        "sam2_video": "SAM2PromptableSegment",
    },
    "SemanticSegment": {
        "beit": "BeitSemanticSegment",
        "deeplabv3": "DeepLabV3SemanticSegment",
        "mobilevit": "MobileViTSemanticSegment",
        "mobilevitv2": "MobileViTV2SemanticSegment",
        "segformer": "SegFormerSemanticSegment",
        "tipsv2_dpt": "Tipsv2DptSemanticSegment",
    },
    "SequenceClassify": {
        "bert": "BertSequenceClassify",
        "deberta": "DebertaSequenceClassify",
        "deberta_v2": "DebertaV2SequenceClassify",
        "deberta_v3": "DebertaV3SequenceClassify",
        "electra": "ElectraSequenceClassify",
        "modernbert": "ModernBertSequenceClassify",
        "roberta": "RobertaSequenceClassify",
        "t5": "T5SequenceClassify",
        "xlm-roberta": "XLMRobertaSequenceClassify",
        "xlm_roberta": "XLMRobertaSequenceClassify",
    },
    "TextEmbed": {
        "clip": "CLIPTextEmbed",
    },
    "TextGenerate": {
        "deepseek_v2": "DeepseekV2TextGenerate",
        "deepseek_v3": "DeepseekV3TextGenerate",
        "deepseek_v4": "DeepseekV4TextGenerate",
        "gemma": "GemmaTextGenerate",
        "gemma2": "Gemma2TextGenerate",
        "gemma3": "Gemma3TextGenerate",
        "gemma3_text": "Gemma3TextGenerate",
        "gemma3n": "Gemma3nTextGenerate",
        "gemma3n_text": "Gemma3nTextGenerate",
        "gemma4": "Gemma4TextGenerate",
        "gemma4_text": "Gemma4UnifiedTextGenerate",
        "gemma4_unified": "Gemma4UnifiedTextGenerate",
        "gemma4_unified_text": "Gemma4UnifiedTextGenerate",
        "glm": "GlmTextGenerate",
        "glm4": "Glm4TextGenerate",
        "glm4_moe": "Glm4MoeTextGenerate",
        "glm4_moe_lite": "Glm4MoeLiteTextGenerate",
        "glm_moe_dsa": "Glm5MoeTextGenerate",
        "gpt2": "GPT2TextGenerate",
        "gpt_oss": "GptOssTextGenerate",
        "llama": "Llama2TextGenerate",
        "llama4": "Llama4TextGenerate",
        "llama4_text": "Llama4TextGenerate",
        "minimax": "MiniMaxTextGenerate",
        "minimax_m2": "MiniMaxM2TextGenerate",
        "mistral": "MistralTextGenerate",
        "mixtral": "MixtralTextGenerate",
        "openai-gpt": "GptTextGenerate",
        "qwen2": "Qwen2TextGenerate",
        "qwen2_5_vl": "Qwen2_5VLTextGenerate",
        "qwen2_5_vl_text": "Qwen2_5VLTextGenerate",
        "qwen2_moe": "Qwen2MoeTextGenerate",
        "qwen2_vl": "Qwen2VLTextGenerate",
        "qwen2_vl_text": "Qwen2VLTextGenerate",
        "qwen3": "Qwen3TextGenerate",
        "qwen3_5": "Qwen3_5TextGenerate",
        "qwen3_5_text": "Qwen3_5TextGenerate",
        "qwen3_moe": "Qwen3MoeTextGenerate",
        "qwen3_next": "Qwen3NextTextGenerate",
        "qwen3_vl": "Qwen3VLTextGenerate",
        "qwen3_vl_moe": "Qwen3VLMoeTextGenerate",
        "qwen3_vl_moe_text": "Qwen3VLMoeTextGenerate",
        "qwen3_vl_text": "Qwen3VLTextGenerate",
    },
    "TextModel": {
        "clip": "CLIPTextModel",
        "gemma3n": "Gemma3nTextModel",
        "gemma3n_text": "Gemma3nTextModel",
        "metaclip_2": "MetaClip2TextModel",
        "owlv2": "Owlv2TextModel",
        "owlvit": "OwlViTTextModel",
        "siglip": "SigLIPTextModel",
        "siglip2": "SigLIP2TextModel",
        "speech_to_text": "Speech2TextModel",
        "tipsv2": "Tipsv2TextModel",
    },
    "TokenClassify": {
        "bert": "BertTokenClassify",
        "deberta": "DebertaTokenClassify",
        "deberta_v2": "DebertaV2TokenClassify",
        "deberta_v3": "DebertaV3TokenClassify",
        "electra": "ElectraTokenClassify",
        "modernbert": "ModernBertTokenClassify",
        "roberta": "RobertaTokenClassify",
        "t5": "T5TokenClassify",
        "xlm-roberta": "XLMRobertaTokenClassify",
        "xlm_roberta": "XLMRobertaTokenClassify",
    },
    "UniversalSegment": {
        "eomt": "EoMTUniversalSegment",
        "mask2former": "Mask2FormerUniversalSegment",
        "maskformer": "MaskFormerUniversalSegment",
        "oneformer": "OneFormerUniversalSegment",
    },
    "VisionModel": {
        "clip": "CLIPVisionModel",
        "metaclip_2": "MetaClip2VisionModel",
        "owlv2": "Owlv2VisionModel",
        "owlvit": "OwlViTVisionModel",
        "siglip": "SigLIPVisionModel",
        "siglip2": "SigLIP2VisionModel",
        "tipsv2": "Tipsv2VisionModel",
    },
    "ZeroShotClassify": {
        "clip": "CLIPZeroShotClassify",
        "metaclip_2": "MetaClip2ZeroShotClassify",
        "siglip": "SigLIPZeroShotClassify",
        "siglip2": "SigLIP2ZeroShotClassify",
    },
}

# The headline table (backbone loader, AutoZModel) as a flat dict, like
# transformers' MODEL_MAPPING_NAMES.
MODEL_MAPPING_NAMES = MODEL_TASK_MAPPING_NAMES["Model"]

# HF model_type values claimed by >1 class within a task (e.g. HF 'deberta-v2' -> both v2
# and v3): {task: {hf_model_type: [candidate class names]}}. The hf: path raises and names
# these candidates instead of guessing; resolve by loading the concrete class. (A zeromodels
# repo is unaffected: its zm_config records a distinct model_type, e.g. 'deberta_v3'.)
AMBIGUOUS_HF_TYPES = {
    "DepthEstimation": {
        "depth_anything": [
            "DepthAnythingV1DepthEstimation",
            "DepthAnythingV2DepthEstimation",
        ],
    },
    "MaskedLM": {
        "deberta-v2": ["DebertaV2MaskedLM", "DebertaV3MaskedLM"],
    },
    "Model": {
        "deberta-v2": ["DebertaV2Model", "DebertaV3Model"],
        "depth_anything": ["DepthAnythingV1Model", "DepthAnythingV2Model"],
        "gemma4": ["Gemma4Model", "Gemma4MultimodalModel"],
        "llama": ["Llama2Model", "LlamaModel"],
        "qwen3_5": ["Qwen3_5Model", "Qwen3_5VLModel"],
        "segformer": ["MiTModel", "SegFormerModel"],
    },
    "MultipleChoice": {
        "deberta-v2": ["DebertaV2MultipleChoice", "DebertaV3MultipleChoice"],
    },
    "QnA": {
        "deberta-v2": ["DebertaV2QnA", "DebertaV3QnA"],
    },
    "SequenceClassify": {
        "deberta-v2": ["DebertaV2SequenceClassify", "DebertaV3SequenceClassify"],
    },
    "TextGenerate": {
        "llama": ["Llama2TextGenerate", "LlamaTextGenerate"],
    },
    "TokenClassify": {
        "deberta-v2": ["DebertaV2TokenClassify", "DebertaV3TokenClassify"],
    },
}

CONFIG_MAPPING_NAMES = {
    "beit": "BeitConfig",
    "bert": "BertConfig",
    "cait": "CaiTConfig",
    "clip": "CLIPConfig",
    "clip_text": "CLIPTextConfig",
    "clip_vision": "CLIPVisionConfig",
    "convmixer": "ConvMixerConfig",
    "convnext": "ConvNeXtConfig",
    "convnextv2": "ConvNeXtV2Config",
    "d_fine": "DFineConfig",
    "deberta": "DebertaConfig",
    "deberta_v2": "DebertaV2Config",
    "deberta_v3": "DebertaV3Config",
    "deeplabv3": "DeepLabV3Config",
    "deepseek_vl": "DeepseekVLConfig",
    "deepseek_vl_hybrid": "DeepseekVLHybridConfig",
    "deepseek_vl_hybrid_high": "DeepseekVLHybridHighResConfig",
    "deepseek_vl_hybrid_text": "DeepseekVLHybridTextConfig",
    "deepseek_vl_hybrid_vision": "DeepseekVLHybridVisionConfig",
    "deepseek_vl_text": "DeepseekVLTextConfig",
    "deepseek_vl_vision": "DeepseekVLVisionConfig",
    "deit": "DeiTConfig",
    "densenet": "DenseNetConfig",
    "depth_anything": "DepthAnythingV1Config",
    "detr": "DetrConfig",
    "dino_resnet": "DinoResNetConfig",
    "dino_vit": "DinoViTConfig",
    "dinov2": "DinoV2Config",
    "dinov3_convnext": "DinoV3ConvNeXtConfig",
    "dinov3_vit": "DinoV3ViTConfig",
    "efficientdet": "EfficientDetConfig",
    "efficientformer": "EfficientFormerConfig",
    "efficientnet": "EfficientNetConfig",
    "efficientnet_lite": "EfficientNetLiteConfig",
    "efficientnetv2": "EfficientNetV2Config",
    "electra": "ElectraConfig",
    "eomt": "EoMTConfig",
    "flexivit": "FlexiViTConfig",
    "gemma": "GemmaConfig",
    "gemma2": "Gemma2Config",
    "gemma3": "Gemma3Config",
    "gemma3_text": "Gemma3TextConfig",
    "gemma3_vision": "Gemma3VisionConfig",
    "gemma3n": "Gemma3nConfig",
    "gemma3n_audio": "Gemma3nAudioConfig",
    "gemma3n_text": "Gemma3nTextConfig",
    "gemma3n_vision": "Gemma3nVisionConfig",
    "gemma4": "Gemma4Config",
    "gemma4_audio": "Gemma4AudioConfig",
    "gemma4_text": "Gemma4TextConfig",
    "gemma4_unified": "Gemma4UnifiedConfig",
    "gemma4_unified_audio": "Gemma4UnifiedAudioConfig",
    "gemma4_unified_vision": "Gemma4UnifiedVisionConfig",
    "gemma4_vision": "Gemma4VisionConfig",
    "glm": "GlmConfig",
    "glm4": "Glm4Config",
    "glm4_moe": "Glm4MoeConfig",
    "glm4_moe_lite": "Glm4MoeLiteConfig",
    "glm4v": "Glm4vConfig",
    "glm4v_moe": "Glm4vMoeConfig",
    "gpt2": "GPT2Config",
    "gpt_oss": "GptOssConfig",
    "granite_speech": "GraniteSpeechConfig",
    "granite_speech5_ctc": "GraniteSpeech5Config",
    "granite_speech_audio": "GraniteSpeechAudioConfig",
    "granite_speech_plus": "GraniteSpeechPlusConfig",
    "granite_speech_text": "GraniteSpeechTextConfig",
    "grounding-dino": "GroundingDinoConfig",
    "inception_next": "InceptionNextConfig",
    "inception_resnetv2": "InceptionResNetV2Config",
    "inceptionv3": "InceptionV3Config",
    "inceptionv4": "InceptionV4Config",
    "internvl": "InternVLConfig",
    "internvl_text": "InternVLTextConfig",
    "internvl_vision": "InternVLVisionConfig",
    "janus": "JanusConfig",
    "janus_text": "JanusTextConfig",
    "janus_vision": "JanusVisionConfig",
    "levit": "LevitConfig",
    "locateanything": "LocateAnythingConfig",
    "locateanything_text": "LocateAnythingTextConfig",
    "locateanything_vision": "LocateAnythingVisionConfig",
    "mask2former": "Mask2FormerConfig",
    "maskformer": "MaskFormerConfig",
    "maxvit": "MaxViTConfig",
    "metaclip_2": "MetaClip2Config",
    "metaclip_2_text": "MetaClip2TextConfig",
    "metaclip_2_vision": "MetaClip2VisionConfig",
    "mit": "MiTConfig",
    "mlp_mixer": "MLPMixerConfig",
    "mobilenetv2": "MobileNetV2Config",
    "mobilenetv3": "MobileNetV3Config",
    "mobilenetv4": "MobileNetV4Config",
    "mobilevit": "MobileViTConfig",
    "mobilevitv2": "MobileViTV2Config",
    "modernbert": "ModernBertConfig",
    "moonshine": "MoonshineConfig",
    "moonshine_audio": "MoonshineAudioConfig",
    "moonshine_text": "MoonshineTextConfig",
    "nextvit": "NextViTConfig",
    "oneformer": "OneFormerConfig",
    "openai-gpt": "GptConfig",
    "owlv2": "Owlv2Config",
    "owlv2_text": "Owlv2TextConfig",
    "owlv2_vision": "Owlv2VisionConfig",
    "owlvit": "OwlViTConfig",
    "owlvit_text": "OwlViTTextConfig",
    "owlvit_vision": "OwlViTVisionConfig",
    "pit": "PiTConfig",
    "poolformer": "PoolFormerConfig",
    "pvt": "PvtConfig",
    "pvt_v2": "PvtV2Config",
    "qwen2": "Qwen2Config",
    "qwen2_5_vl": "Qwen2_5VLConfig",
    "qwen2_5_vl_text": "Qwen2_5VLTextConfig",
    "qwen2_5_vl_vision": "Qwen2_5VLVisionConfig",
    "qwen2_moe": "Qwen2MoeConfig",
    "qwen2_vl": "Qwen2VLConfig",
    "qwen2_vl_text": "Qwen2VLTextConfig",
    "qwen2_vl_vision": "Qwen2VLVisionConfig",
    "qwen3": "Qwen3Config",
    "qwen3_5": "Qwen3_5Config",
    "qwen3_5_moe": "Qwen3_5MoeConfig",
    "qwen3_5_moe_text": "Qwen3_5MoeTextConfig",
    "qwen3_5_moe_vision": "Qwen3_5MoeVisionConfig",
    "qwen3_5_text": "Qwen3_5TextConfig",
    "qwen3_5_vision": "Qwen3_5VisionConfig",
    "qwen3_moe": "Qwen3MoeConfig",
    "qwen3_next": "Qwen3NextConfig",
    "qwen3_vl": "Qwen3VLConfig",
    "qwen3_vl_moe": "Qwen3VLMoeConfig",
    "qwen3_vl_moe_text": "Qwen3VLMoeTextConfig",
    "qwen3_vl_moe_vision": "Qwen3VLMoeVisionConfig",
    "qwen3_vl_text": "Qwen3VLTextConfig",
    "qwen3_vl_vision": "Qwen3VLVisionConfig",
    "regnet": "RegNetConfig",
    "res2net": "Res2NetConfig",
    "resmlp": "ResMLPConfig",
    "resnet": "ResNetConfig",
    "resnetv2": "ResNetV2Config",
    "resnext": "ResNeXtConfig",
    "rf_detr": "RFDetrConfig",
    "roberta": "RobertaConfig",
    "rt_detr": "RTDetrConfig",
    "rt_detr_v2": "RTDetrV2Config",
    "sam": "SamConfig",
    "sam2": "Sam2Config",
    "sam3": "Sam3Config",
    "segformer": "SegformerConfig",
    "senet": "SENetConfig",
    "siglip": "SigLIPConfig",
    "siglip2": "Siglip2Config",
    "siglip2_text": "Siglip2TextConfig",
    "siglip_text": "SigLIPTextConfig",
    "siglip_vision": "SigLIPVisionConfig",
    "speech_to_text": "Speech2TextConfig",
    "speech_to_text_audio": "Speech2TextAudioConfig",
    "speech_to_text_text": "Speech2TextTextConfig",
    "swin": "SwinConfig",
    "swinv2": "SwinV2Config",
    "t5": "T5Config",
    "table-transformer": "TableTransformerConfig",
    "tipsv2": "Tipsv2Config",
    "tipsv2_dpt": "Tipsv2DptConfig",
    "tipsv2_text": "Tipsv2TextConfig",
    "tipsv2_vision": "Tipsv2VisionConfig",
    "vgg": "VGGConfig",
    "vit": "ViTConfig",
    "whisper": "WhisperConfig",
    "whisper_audio": "WhisperAudioConfig",
    "whisper_text": "WhisperTextConfig",
    "xception": "XceptionConfig",
    "xlm_roberta": "XLMRobertaConfig",
}

TOKENIZER_MAPPING_NAMES = {
    "bert": "BertTokenizer",
    "clip": "CLIPTokenizer",
    "deberta": "DebertaTokenizer",
    "deberta-v2": "DebertaV2Tokenizer",
    "deberta_v2": "DebertaV2Tokenizer",
    "deberta_v3": "DebertaV3Tokenizer",
    "deepseek_v2": "DeepseekV2Tokenizer",
    "deepseek_v3": "DeepseekV3Tokenizer",
    "deepseek_v4": "DeepseekV4Tokenizer",
    "deepseek_vl": "DeepseekVLTokenizer",
    "deepseek_vl_hybrid": "DeepseekVLHybridTokenizer",
    "electra": "ElectraTokenizer",
    "gemma": "GemmaTokenizer",
    "gemma2": "Gemma2Tokenizer",
    "gemma3": "Gemma3Tokenizer",
    "gemma3_text": "Gemma3Tokenizer",
    "gemma3n": "Gemma3nTokenizer",
    "gemma3n_text": "Gemma3nTokenizer",
    "gemma4": "Gemma4Tokenizer",
    "gemma4_text": "Gemma4Tokenizer",
    "gemma4_unified": "Gemma4UnifiedTokenizer",
    "gemma4_unified_text": "Gemma4UnifiedTokenizer",
    "glm": "GlmTokenizer",
    "glm4": "Glm4Tokenizer",
    "glm4_moe": "Glm4MoeTokenizer",
    "glm4_moe_lite": "Glm4MoeLiteTokenizer",
    "glm4v": "Glm4vTokenizer",
    "glm4v_moe": "Glm4vMoeTokenizer",
    "glm_moe_dsa": "Glm5MoeTokenizer",
    "gpt2": "GPT2Tokenizer",
    "gpt_oss": "GptOssTokenizer",
    "granite_speech": "GraniteSpeechTokenizer",
    "granite_speech5_ctc": "GraniteSpeech5Tokenizer",
    "granite_speech_plus": "GraniteSpeechPlusTokenizer",
    "grounding-dino": "GroundingDinoTokenizer",
    "internvl": "InternVLTokenizer",
    "janus": "JanusTokenizer",
    "kimi_k25": "KimiK25Tokenizer",
    "llama": "LlamaTokenizer",
    "llama4": "Llama4Tokenizer",
    "llama4_text": "Llama4Tokenizer",
    "locateanything": "LocateAnythingTokenizer",
    "metaclip_2": "MetaClip2Tokenizer",
    "minimax": "MiniMaxTokenizer",
    "minimax_m2": "MiniMaxM2Tokenizer",
    "minimax_m3_vl": "MiniMaxM3VLTokenizer",
    "mistral": "MistralTokenizer",
    "mistral3": "Mistral3Tokenizer",
    "mixtral": "MixtralTokenizer",
    "modernbert": "ModernBertTokenizer",
    "moonshine": "MoonshineTokenizer",
    "oneformer": "OneFormerTokenizer",
    "openai-gpt": "GptTokenizer",
    "owlv2": "Owlv2Tokenizer",
    "owlvit": "OwlViTTokenizer",
    "qwen2": "Qwen2Tokenizer",
    "qwen2_moe": "Qwen2MoeTokenizer",
    "qwen2_vl": "Qwen2VLTokenizer",
    "qwen2_vl_text": "Qwen2VLTokenizer",
    "qwen3": "Qwen3Tokenizer",
    "qwen3_5": "Qwen3_5Tokenizer",
    "qwen3_5_moe": "Qwen3_5MoeTokenizer",
    "qwen3_5_moe_text": "Qwen3_5MoeTokenizer",
    "qwen3_5_text": "Qwen3_5Tokenizer",
    "qwen3_moe": "Qwen3MoeTokenizer",
    "qwen3_next": "Qwen3NextTokenizer",
    "qwen3_vl_moe": "Qwen3VLMoeTokenizer",
    "qwen3_vl_moe_text": "Qwen3VLMoeTokenizer",
    "roberta": "RobertaTokenizer",
    "sam3": "SAM3CLIPTokenizer",
    "siglip": "SigLIPTokenizer",
    "siglip2": "SigLIP2Tokenizer",
    "speech_to_text": "Speech2TextTokenizer",
    "t5": "T5Tokenizer",
    "tipsv2": "Tipsv2Tokenizer",
    "whisper": "WhisperTokenizer",
    "xlm-roberta": "XLMRobertaTokenizer",
    "xlm_roberta": "XLMRobertaTokenizer",
}

PROCESSOR_MAPPING_NAMES = {
    "clip": "CLIPProcessor",
    "deepseek_vl": "DeepseekVLProcessor",
    "deepseek_vl_hybrid": "DeepseekVLHybridProcessor",
    "gemma3": "Gemma3Processor",
    "gemma3_text": "Gemma3Processor",
    "gemma3n": "Gemma3nProcessor",
    "gemma3n_text": "Gemma3nProcessor",
    "gemma4": "Gemma4Processor",
    "gemma4_text": "Gemma4Processor",
    "gemma4_unified": "Gemma4UnifiedProcessor",
    "gemma4_unified_text": "Gemma4UnifiedProcessor",
    "glm4v": "Glm4vProcessor",
    "glm4v_moe": "Glm4vMoeProcessor",
    "granite_speech": "GraniteSpeechProcessor",
    "granite_speech5_ctc": "GraniteSpeech5Processor",
    "granite_speech_plus": "GraniteSpeechPlusProcessor",
    "grounding-dino": "GroundingDinoProcessor",
    "internvl": "InternVLProcessor",
    "janus": "JanusProcessor",
    "kimi_k25": "KimiK25Processor",
    "locateanything": "LocateAnythingProcessor",
    "metaclip_2": "MetaClip2Processor",
    "minimax_m3_vl": "MiniMaxM3VLProcessor",
    "mistral3": "Mistral3Processor",
    "moonshine": "MoonshineProcessor",
    "oneformer": "OneFormerProcessor",
    "owlv2": "Owlv2Processor",
    "owlvit": "OwlViTProcessor",
    "qwen2_5_vl": "Qwen2VLProcessor",
    "qwen2_5_vl_text": "Qwen2VLProcessor",
    "qwen2_vl": "Qwen2VLProcessor",
    "qwen2_vl_text": "Qwen2VLProcessor",
    "qwen3_5": "Qwen3_5Processor",
    "qwen3_5_moe": "Qwen3_5MoeProcessor",
    "qwen3_5_moe_text": "Qwen3_5MoeProcessor",
    "qwen3_5_text": "Qwen3_5Processor",
    "qwen3_vl": "Qwen3VLProcessor",
    "qwen3_vl_moe": "Qwen3VLMoeProcessor",
    "qwen3_vl_moe_text": "Qwen3VLMoeProcessor",
    "qwen3_vl_text": "Qwen3VLProcessor",
    "sam3": "SAM3Processor",
    "siglip": "SigLIPProcessor",
    "siglip2": "SigLIP2Processor",
    "speech_to_text": "Speech2TextProcessor",
    "tipsv2": "Tipsv2Processor",
    "whisper": "WhisperProcessor",
}

IMAGE_PROCESSOR_MAPPING_NAMES = {
    "beit": "BeitImageProcessor",
    "cait": "CaiTImageProcessor",
    "clip": "CLIPImageProcessor",
    "convmixer": "ConvMixerImageProcessor",
    "convnext": "ConvNeXtImageProcessor",
    "convnextv2": "ConvNeXtV2ImageProcessor",
    "d_fine": "DFineImageProcessor",
    "deeplabv3": "DeepLabV3ImageProcessor",
    "deepseek_vl": "DeepseekVLImageProcessor",
    "deepseek_vl_hybrid": "DeepseekVLHybridImageProcessor",
    "deit": "DeiTImageProcessor",
    "densenet": "DenseNetImageProcessor",
    "depth_anything": "DepthAnythingV1ImageProcessor",
    "detr": "DETRImageProcessor",
    "dfine": "DFineImageProcessor",
    "dino_resnet": "DinoImageProcessor",
    "dino_vit": "DinoImageProcessor",
    "dinov2": "DinoV2ImageProcessor",
    "dinov3_convnext": "DinoV3ImageProcessor",
    "dinov3_vit": "DinoV3ImageProcessor",
    "efficientdet": "EfficientDetImageProcessor",
    "efficientformer": "EfficientFormerImageProcessor",
    "efficientnet": "EfficientNetImageProcessor",
    "efficientnet_lite": "EfficientNetLiteImageProcessor",
    "efficientnetv2": "EfficientNetV2ImageProcessor",
    "eomt": "EoMTImageProcessor",
    "flexivit": "FlexiViTImageProcessor",
    "gemma3": "Gemma3ImageProcessor",
    "gemma3_text": "Gemma3ImageProcessor",
    "gemma3n": "Gemma3nImageProcessor",
    "gemma3n_text": "Gemma3nImageProcessor",
    "gemma4": "Gemma4ImageProcessor",
    "gemma4_text": "Gemma4ImageProcessor",
    "gemma4_unified": "Gemma4UnifiedImageProcessor",
    "gemma4_unified_text": "Gemma4UnifiedImageProcessor",
    "glm4v": "Glm4vImageProcessor",
    "grounding-dino": "GroundingDinoImageProcessor",
    "inception_next": "InceptionNextImageProcessor",
    "inception_resnetv2": "InceptionResNetV2ImageProcessor",
    "inceptionv3": "InceptionV3ImageProcessor",
    "inceptionv4": "InceptionV4ImageProcessor",
    "internvl": "InternVLImageProcessor",
    "janus": "JanusImageProcessor",
    "kimi_k25": "KimiK25ImageProcessor",
    "levit": "LevitImageProcessor",
    "locateanything": "LocateAnythingImageProcessor",
    "mask2former": "Mask2FormerImageProcessor",
    "maskformer": "MaskFormerImageProcessor",
    "maxvit": "MaxViTImageProcessor",
    "metaclip_2": "MetaClip2ImageProcessor",
    "minimax_m3_vl": "MiniMaxM3VLImageProcessor",
    "mistral3": "Mistral3ImageProcessor",
    "mit": "MiTImageProcessor",
    "mlp_mixer": "MLPMixerImageProcessor",
    "mobilenetv2": "MobileNetV2ImageProcessor",
    "mobilenetv3": "MobileNetV3ImageProcessor",
    "mobilenetv4": "MobileNetV4ImageProcessor",
    "mobilevit": "MobileViTImageProcessor",
    "mobilevitv2": "MobileViTV2ImageProcessor",
    "nextvit": "NextViTImageProcessor",
    "oneformer": "OneFormerImageProcessor",
    "owlv2": "Owlv2ImageProcessor",
    "owlvit": "OwlViTImageProcessor",
    "pit": "PiTImageProcessor",
    "poolformer": "PoolFormerImageProcessor",
    "pvt": "PvtImageProcessor",
    "pvt_v2": "PvtV2ImageProcessor",
    "qwen2_vl": "Qwen2VLImageProcessor",
    "qwen2_vl_text": "Qwen2VLImageProcessor",
    "regnet": "RegNetImageProcessor",
    "res2net": "Res2NetImageProcessor",
    "resmlp": "ResMLPImageProcessor",
    "resnet": "ResNetImageProcessor",
    "resnetv2": "ResNetV2ImageProcessor",
    "resnext": "ResNeXtImageProcessor",
    "rf_detr": "RFDETRImageProcessor",
    "rt_detr": "RTDETRImageProcessor",
    "rt_detr_v2": "RTDETRV2ImageProcessor",
    "sam": "SAMImageProcessor",
    "sam2": "SAM2ImageProcessor",
    "sam2_video": "SAM2ImageProcessor",
    "sam3": "SAM3ImageProcessor",
    "segformer": "MiTImageProcessor",
    "senet": "SENetImageProcessor",
    "siglip": "SigLIPImageProcessor",
    "siglip2": "SigLIP2ImageProcessor",
    "swin": "SwinImageProcessor",
    "swinv2": "SwinV2ImageProcessor",
    "table-transformer": "TableTransformerImageProcessor",
    "tipsv2": "Tipsv2ImageProcessor",
    "tipsv2_dpt": "Tipsv2DptImageProcessor",
    "vgg": "VGGImageProcessor",
    "vit": "ViTImageProcessor",
    "xception": "XceptionImageProcessor",
}
