MIXTRAL_CONFIG = {
    "mixtral-8x7b": {
        "vocab_size": 32000,
        "embed_dim": 4096,
        "mlp_dim": 14336,
        "num_layers": 32,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "num_experts": 8,
        "num_experts_per_tok": 2,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "sliding_window": None,
        "tie_embeddings": False,
    },
    "mixtral-8x7b-instruct": {
        "vocab_size": 32000,
        "embed_dim": 4096,
        "mlp_dim": 14336,
        "num_layers": 32,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "num_experts": 8,
        "num_experts_per_tok": 2,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "sliding_window": None,
        "tie_embeddings": False,
    },
    "mixtral-8x22b": {
        "vocab_size": 32768,
        "embed_dim": 6144,
        "mlp_dim": 16384,
        "num_layers": 56,
        "num_heads": 48,
        "num_kv_heads": 8,
        "head_dim": 128,
        "num_experts": 8,
        "num_experts_per_tok": 2,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "sliding_window": None,
        "tie_embeddings": False,
    },
    "mixtral-8x22b-instruct": {
        "vocab_size": 32768,
        "embed_dim": 6144,
        "mlp_dim": 16384,
        "num_layers": 56,
        "num_heads": 48,
        "num_kv_heads": 8,
        "head_dim": 128,
        "num_experts": 8,
        "num_experts_per_tok": 2,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "sliding_window": None,
        "tie_embeddings": False,
    },
}

MIXTRAL_WEIGHTS_URLS = {
    "mixtral-8x7b": {
        "hf_id": "mistralai/Mixtral-8x7B-v0.1",
        "gated": True,
        "safetensors": True,
    },
    "mixtral-8x7b-instruct": {
        "hf_id": "mistralai/Mixtral-8x7B-Instruct-v0.1",
        "gated": True,
        "safetensors": True,
    },
    "mixtral-8x22b": {
        "hf_id": "mistralai/Mixtral-8x22B-v0.1",
        "gated": True,
        "safetensors": True,
    },
    "mixtral-8x22b-instruct": {
        "hf_id": "mistralai/Mixtral-8x22B-Instruct-v0.1",
        "gated": True,
        "safetensors": True,
    },
}
