MISTRAL_CONFIG = {
    "mistral-7b-v0.1": {
        "vocab_size": 32000,
        "embed_dim": 4096,
        "mlp_dim": 14336,
        "num_layers": 32,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 10000.0,
        "sliding_window": 4096,
        "tie_embeddings": False,
    },
    "mistral-7b-instruct-v0.2": {
        "vocab_size": 32000,
        "embed_dim": 4096,
        "mlp_dim": 14336,
        "num_layers": 32,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "sliding_window": None,
        "tie_embeddings": False,
    },
    "mistral-7b-v0.3": {
        "vocab_size": 32768,
        "embed_dim": 4096,
        "mlp_dim": 14336,
        "num_layers": 32,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "sliding_window": None,
        "tie_embeddings": False,
    },
    "mistral-7b-instruct-v0.3": {
        "vocab_size": 32768,
        "embed_dim": 4096,
        "mlp_dim": 14336,
        "num_layers": 32,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "sliding_window": None,
        "tie_embeddings": False,
    },
    "ministral-8b-instruct-2410": {
        "vocab_size": 131072,
        "embed_dim": 4096,
        "mlp_dim": 12288,
        "num_layers": 36,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 100000000.0,
        "sliding_window": 32768,
        "tie_embeddings": False,
    },
    "mistral-nemo-base-2407": {
        "vocab_size": 131072,
        "embed_dim": 5120,
        "mlp_dim": 14336,
        "num_layers": 40,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "sliding_window": None,
        "tie_embeddings": False,
    },
    "mistral-nemo-instruct-2407": {
        "vocab_size": 131072,
        "embed_dim": 5120,
        "mlp_dim": 14336,
        "num_layers": 40,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "sliding_window": None,
        "tie_embeddings": False,
    },
    "mistral-small-24b-base-2501": {
        "vocab_size": 131072,
        "embed_dim": 5120,
        "mlp_dim": 32768,
        "num_layers": 40,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 100000000.0,
        "sliding_window": None,
        "tie_embeddings": False,
    },
    "mistral-small-24b-instruct-2501": {
        "vocab_size": 131072,
        "embed_dim": 5120,
        "mlp_dim": 32768,
        "num_layers": 40,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-5,
        "rope_theta": 100000000.0,
        "sliding_window": None,
        "tie_embeddings": False,
    },
}

MISTRAL_WEIGHTS_URLS = {
    "mistral-7b-v0.1": {
        "hf_id": "mistralai/Mistral-7B-v0.1",
        "gated": True,
        "safetensors": True,
    },
    "mistral-7b-instruct-v0.2": {
        "hf_id": "mistralai/Mistral-7B-Instruct-v0.2",
        "gated": True,
        "safetensors": True,
    },
    "mistral-7b-v0.3": {
        "hf_id": "mistralai/Mistral-7B-v0.3",
        "gated": True,
        "safetensors": True,
    },
    "mistral-7b-instruct-v0.3": {
        "hf_id": "mistralai/Mistral-7B-Instruct-v0.3",
        "gated": True,
        "safetensors": True,
    },
    "ministral-8b-instruct-2410": {
        "hf_id": "mistralai/Ministral-8B-Instruct-2410",
        "gated": True,
        "safetensors": True,
    },
    "mistral-nemo-base-2407": {
        "hf_id": "mistralai/Mistral-Nemo-Base-2407",
        "gated": True,
        "safetensors": True,
    },
    "mistral-nemo-instruct-2407": {
        "hf_id": "mistralai/Mistral-Nemo-Instruct-2407",
        "gated": True,
        "safetensors": True,
    },
    "mistral-small-24b-base-2501": {
        "hf_id": "mistralai/Mistral-Small-24B-Base-2501",
        "gated": True,
        "safetensors": True,
    },
    "mistral-small-24b-instruct-2501": {
        "hf_id": "mistralai/Mistral-Small-24B-Instruct-2501",
        "gated": True,
        "safetensors": True,
    },
}
