LLAMA4_CONFIG = {
    "llama4-scout-17b-16e": {
        "vocab_size": 202048,
        "embed_dim": 5120,
        "mlp_dim": 8192,
        "dense_mlp_dim": 16384,
        "num_layers": 48,
        "num_heads": 40,
        "num_kv_heads": 8,
        "head_dim": 128,
        "num_experts": 16,
        "num_experts_per_tok": 1,
        "interleave_moe_layer_step": 1,
        "no_rope_layer_interval": 4,
        "attention_chunk_size": 8192,
        "use_qk_norm": True,
        "attn_temperature_tuning": True,
        "floor_scale": 8192.0,
        "attn_scale": 0.1,
        "norm_eps": 1e-5,
        "rope_theta": 500000.0,
        "rope_factor": 16.0,
        "rope_low_freq_factor": 1.0,
        "rope_high_freq_factor": 1.0,
        "rope_original_max_pos": 8192,
        "tie_embeddings": False,
    },
    "llama4-scout-17b-16e-instruct": {
        "vocab_size": 202048,
        "embed_dim": 5120,
        "mlp_dim": 8192,
        "dense_mlp_dim": 16384,
        "num_layers": 48,
        "num_heads": 40,
        "num_kv_heads": 8,
        "head_dim": 128,
        "num_experts": 16,
        "num_experts_per_tok": 1,
        "interleave_moe_layer_step": 1,
        "no_rope_layer_interval": 4,
        "attention_chunk_size": 8192,
        "use_qk_norm": True,
        "attn_temperature_tuning": True,
        "floor_scale": 8192.0,
        "attn_scale": 0.1,
        "norm_eps": 1e-5,
        "rope_theta": 500000.0,
        "rope_factor": 16.0,
        "rope_low_freq_factor": 1.0,
        "rope_high_freq_factor": 1.0,
        "rope_original_max_pos": 8192,
        "tie_embeddings": False,
    },
    "llama4-maverick-17b-128e": {
        "vocab_size": 202048,
        "embed_dim": 5120,
        "mlp_dim": 8192,
        "dense_mlp_dim": 16384,
        "num_layers": 48,
        "num_heads": 40,
        "num_kv_heads": 8,
        "head_dim": 128,
        "num_experts": 128,
        "num_experts_per_tok": 1,
        "interleave_moe_layer_step": 2,
        "no_rope_layer_interval": 4,
        "attention_chunk_size": 8192,
        "use_qk_norm": False,
        "attn_temperature_tuning": True,
        "floor_scale": 8192.0,
        "attn_scale": 0.1,
        "norm_eps": 1e-5,
        "rope_theta": 500000.0,
        "rope_factor": None,
        "rope_low_freq_factor": 1.0,
        "rope_high_freq_factor": 1.0,
        "rope_original_max_pos": 8192,
        "tie_embeddings": False,
    },
    "llama4-maverick-17b-128e-instruct": {
        "vocab_size": 202048,
        "embed_dim": 5120,
        "mlp_dim": 8192,
        "dense_mlp_dim": 16384,
        "num_layers": 48,
        "num_heads": 40,
        "num_kv_heads": 8,
        "head_dim": 128,
        "num_experts": 128,
        "num_experts_per_tok": 1,
        "interleave_moe_layer_step": 2,
        "no_rope_layer_interval": 4,
        "attention_chunk_size": 8192,
        "use_qk_norm": False,
        "attn_temperature_tuning": True,
        "floor_scale": 8192.0,
        "attn_scale": 0.1,
        "norm_eps": 1e-5,
        "rope_theta": 500000.0,
        "rope_factor": None,
        "rope_low_freq_factor": 1.0,
        "rope_high_freq_factor": 1.0,
        "rope_original_max_pos": 8192,
        "tie_embeddings": False,
    },
}

LLAMA4_WEIGHTS_URLS = {
    "llama4-scout-17b-16e": {
        "hf_id": "meta-llama/Llama-4-Scout-17B-16E",
        "gated": True,
        "safetensors": True,
    },
    "llama4-scout-17b-16e-instruct": {
        "hf_id": "meta-llama/Llama-4-Scout-17B-16E-Instruct",
        "gated": True,
        "safetensors": True,
    },
    "llama4-maverick-17b-128e": {
        "hf_id": "meta-llama/Llama-4-Maverick-17B-128E",
        "gated": True,
        "safetensors": True,
    },
    "llama4-maverick-17b-128e-instruct": {
        "hf_id": "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
        "gated": True,
        "safetensors": True,
    },
}
